### ISSUE TITLE
Shorter HLD

### ISSUE THREAD

**Issue by simonlindholm** [kth-competitive-programming/kactl#12]
https://github.com/TimonKnigge/TCR/tree/master/snippets/graphs seems to have a very short one. Also http://codeforces.com/blog/entry/22072.

**Comment by Chillee** [comment]
I propose we remove KACTL's for Benq's. I know we've had discussions about removing it entirely, but I think there's value in having the more straightforward one around (that more people understand).

There's also the matter of the subtree modifications trick: https://codeforces.com/blog/entry/53170

The same *can* be done with LCT's, but I think that's messy. There's also another data structure called AAA-trees (also called self adjusting top trees) that supports subtree/path modification/query but that's a whole nother discussion.

**Comment by simonlindholm** [comment]
Fixed in #155.
