### ISSUE TITLE
Directed MST edge reconstruction

### ISSUE THREAD

**Issue by simonlindholm** [kth-competitive-programming/kactl#120]
The arborescence implementation added in #110 does not support reconstructing the edges. Might be nice to have if it's not too long.

**Comment by Chillee** [comment]
https://github.com/bqi343/USACO/blob/master/Implementations/content/graphs%20(12)/Fundamentals/ManhattanMST.h

**Comment by simonlindholm** [comment]
Did some experimentation with this over in https://github.com/simonlindholm/kactl/tree/dmst-reconstruction, got it down to 15 new lines, but I have some bug in my rewrite, and the linked impl turns out to be buggy as well: https://github.com/bqi343/USACO/issues/11

**Comment by Chillee** [comment]
That is unfortunate... :'(
