### ISSUE TITLE
Make `linearRecurrence` more permissive

### ISSUE THREAD

**Issue by ecnerwala** [kth-competitive-programming/kactl#123]
As of now, `linearRec` requires that exactly the correct number of initial conditions be given. This is somewhat annoying with `BerlekampMassey`, where we generate many more initial terms than we need. We might as well make it more permissive, letting it take more terms if desired.

To fix it, just change `sz(S)` to `sz(tr)` in this line: https://github.com/kth-competitive-programming/kactl/blob/b6231f39445155fc3eeaa1dee150ba1f86464738/content/numerical/LinearRecurrence.h#L21

**Comment by simonlindholm** [comment]
Good point, fixed.
