### ISSUE TITLE
Precompute powers of roots in NTT

### ISSUE THREAD

**Issue by aryanc403** [kth-competitive-programming/kactl#151]
Init function https://github.com/ecnerwala/icpc-book/blob/master/content/numerical/fft.cpp
init_fft in https://github.com/Ashishgup1/Competitive-Coding/blob/master/FFT%20(Recursive).cpp  

Precomputing powers of roots similar to above FFT's should reduce constant factor. Right now NTT computes them in every convolution.  

Constant factor did reduce by 3-4 times when this optimisation on https://www.codechef.com/viewsolution/26468080

**Comment by simonlindholm** [comment]
Current code for reference: https://github.com/kth-competitive-programming/kactl/blob/939b5cd647f8bd27cad4a93ff9ee2513bafcfb3e/content/numerical/NumberTheoreticTransform.h

We should be able to do what the FFT does and keep a static vector of roots around, without any API changes.
