### ISSUE TITLE
Proof of modmul correctness takes a false assumption on windows

### ISSUE THREAD

**Issue by eric-wieser** [kth-competitive-programming/kactl#185]
https://github.com/kth-competitive-programming/kactl/blob/e865c06c197db90516f136b4710389dcdd45086c/doc/modmul-proof.tex#L53

On windows, the precision of `long double` is exactly the same as the precision of `double` - the C++ standard does not specify the required precision.

**Comment by simonlindholm** [comment]
Thanks, noted in the description and changed a bunch of x86 to x87 to make the assumption clear.
