### ISSUE TITLE
The modmul definition uses M which is not defined anywhere

### ISSUE THREAD

**Issue by huynhtrankhanh** [kth-competitive-programming/kactl#186]
https://github.com/kth-competitive-programming/kactl/blob/master/doc/modmul-proof.md

In this line:
```cpp
i64 ret = a * b - M * u64(ld(a) * ld(b) / ld(c));
```

Is `M` a typo?

**Comment by huynhtrankhanh** [comment]
Note: this doesn't affect the _actual_ modmul code, only the proof.

**Comment by simonlindholm** [comment]
Yes, it's a typo. Fixed, thanks!
