### ISSUE TITLE
Dinic

### ISSUE THREAD

**Issue by simonlindholm** [kth-competitive-programming/kactl#19]
https://github.com/TimonKnigge/TCR/blob/master/snippets/flowalgorithms/dinic_ragnar.cpp is short, and might be worth including in case push-relabel falls down on some case.

**Comment by ludopulles** [comment]
Link is dead, consider https://github.com/TimonKnigge/TCR/blob/master/snippets/flowalgorithms/dinic.cpp

**Comment by simonlindholm** [comment]
I guess we can remove Hopcroft-Karp when we add Dinic, to win back space.

**Comment by ludopulles** [comment]
Do you also still need EdmondsKarp in this case? Otherwise, it would give PushRelabel, Dinic and EdmondsKarp as flow options. While  the last two have the same complexity.

**Comment by Chillee** [comment]
EdmondsKarp is VE^2, while Dinic is EV^2. Dinic's also has a lot of nice properties on things like unit graphs or bipartite matching graphs too (`VE^(1/2)` for bipartite matching graphs, and `min(V^(1/2), E^(2/3))E` on unit graphs).

**Comment by Chillee** [comment]
I think this issue, at least, is resolved. There's another discussion to be had about the "Flow algorithm" situation.

**Comment by simonlindholm** [comment]
Yep.
