### ISSUE TITLE
In whole Geometry section, there are no epsilon.

### ISSUE THREAD

**Issue by reKelin** [kth-competitive-programming/kactl#197]
In whole Geometry section, there are no epsilon.

**Comment by simonlindholm** [comment]
There are epsilons in a few places, but generally speaking:
- you typically want to use integers, which don't need epsilons
- there is no universal epsilon, or way of using epsilons
- for many algorithms when comparing two floats `x < y` and `x` and `y` are approximately equal, either result is fine
- if epsilons are needed, the changes are simple and can be done manually
