### ISSUE TITLE
Make string hashing ARM-friendly

### ISSUE THREAD

**Issue by ParthKohli** [kth-competitive-programming/kactl#215]
Hi, it would be nice to either have the operators operator< and operator== defined for H in Hashing-codeforces.h or remove the reliance of assembly instructions in Hashing.h (they are not natively compatible with my M1 Mac).

**Comment by simonlindholm** [comment]
Did both of those things in ca294f4249d78d3a462040024689bbb2615a6d84 and 58b984d1556e9bae4366d49365b4655cb358a6a6. Turns out GCC is able to detect the add-with-carry pattern well enough now that it's actually a slight perf *win* on x86-64, by getting rid of a mov. Aarch64 asm looks good too:
```
H::operator*(H) [clone .isra.0]:
        mul     x2, x1, x0
        umulh   x1, x1, x0
        adds    x0, x2, x1
        cinc    x0, x0, cs
        ret
H::operator+(H) [clone .isra.0]:
        adds    x0, x1, x0
        cinc    x0, x0, cs
        ret
```
