### ISSUE TITLE
CRT for large numbers

### ISSUE THREAD

**Issue by simonlindholm** [kth-competitive-programming/kactl#27]
Requiring each to be <2^31 can be annoying. Maybe CRT for many small numbers simultaneously would help?

**Comment by Chillee** [comment]
I don't think this is really an issue. We can just use `__int128_t` if needed. It might be a good idea to make `CRT` templated to facilitate that.

**Comment by simonlindholm** [comment]
Sure, but it's a subtle gotcha that it can overflow even though `mn < 2^63`. Fixed that in 12af084b29e7122530171141bb98684fde0a658e. For larger numbers than that I'm fine with `__int128_t` ([Garner's algorithm](https://cp-algorithms.com/algebra/chinese-remainder-theorem.html) is faster for many small numbers, but that probably doesn't matter in practice.)
