### ISSUE TITLE
Runtime Error with Convexhull.h

### ISSUE THREAD

**Issue by DeMen100ns** [kth-competitive-programming/kactl#271]
Recently, i use the `Convexhull.h` to submit problem 2195 on CSES. It passed almost of tests, except one test: 
```
4
3 2
1 5
3 6
3 5
```

the judge returned error:
```
code: malloc.c:2617: sysmalloc: Assertion `(old_top == initial_top (av) && old_size == 0) || ((unsigned long) (old_size) >= MINSIZE && prev_inuse (old_top) && ((unsigned long) old_end & (pagesize - 1)) == 0)' failed.
```

Here is link of my implementation: [Link](https://cses.fi/paste/505c9b224833e559a339f5/)

I have ran the test in local and it returned the correct answer.

**Comment by bjorn-martinsson** [comment]
I just took a quick glance, but you have clearly modified the code from ConvexHull.h.

```cpp
h[t-2].cross(h[t-1], p) < 0
```

vs 

```cpp
h[t-2].cross(h[t-1], p) <= 0
```
