### ISSUE TITLE
Hashing.h in PDF contains asm instructions

### ISSUE THREAD

**Issue by jilljenn** [kth-competitive-programming/kactl#275]
![image](https://github.com/user-attachments/assets/0cb8470c-31d1-43d9-b0b3-5ab31459e3ad)

Because of the asm instructions it does not seem to work on an example. Where do they come from?
If we take Hashing.h it does work.

**Comment by simonlindholm** [comment]
Sorry, hadn't committed an up-to-date kactl.pdf in forever. Done in 08896e6022bc77e55f7b352aa540b7784a5206f3.
