### ISSUE TITLE
Translate techniques.txt to English

### ISSUE THREAD

**Issue by Tyilo** [kth-competitive-programming/kactl#29]
It seems weird that `troubleshoot.txt` is in English, but `techniques.txt` is not.
Also this would make `techniques.txt` useful for non-Swedish participants.

**Comment by simonlindholm** [comment]
That's fair -- done in 37914d7956ed42889e91202e809b7064f70ebf2f. Still quite cryptic, and I'm not sure the list is useful to anyone but @jsannemo.
