### ISSUE TITLE
Visibility outside/inside polygon

### ISSUE THREAD

**Issue by simonlindholm** [kth-competitive-programming/kactl#4]
Can point A see point B, or is the way blocked by the polygon? Edges can be seen along, otherwise it's simple.

**Comment by Chillee** [comment]
I don't see why this isn't trivial? Take the `segInter` function, and change it a little to return `true` only if its intersection is "proper" (ie: not on one of the endpoints).

Then simply iterate through all edges in a polygon.

**Comment by simonlindholm** [comment]
Nope, if the line A-B goes through a vertex that doesn't work.

(This issue comes from a one-off remark Johan made at some point IIRC, it might very well not be sufficiently general-purpose to include...)

**Comment by simonlindholm** [comment]
Yeah, this seems too special-purpose, closing.
