### ISSUE TITLE
Improve ModMull

### ISSUE THREAD

**Issue by Chillee** [kth-competitive-programming/kactl#70]
I don't really understand why we have `mod_mul`. If we're not supporting 32 bit (ie: CF), can't we juts use `__int128_t`?

Alternately, we can use the equivalent of this: https://github.com/RamchandraApte/OmniTemplate/blob/master/modulo.h#L23

The current KACTL one is slower (by 5-20x), has that annoying `bit` thing, and is longer.

**Comment by simonlindholm** [comment]
Let's close this now, I guess?
