### ISSUE TITLE
Add custom hash function for `gp_hash_table`

### ISSUE THREAD

**Issue by Chillee** [kth-competitive-programming/kactl#86]
https://github.com/ecnerwala/icpc-book/blob/master/content/various/Hashmap.h

Also see my blog post: https://codeforces.com/blog/entry/60737

**Comment by simonlindholm** [comment]
This already exists: https://github.com/kth-competitive-programming/kactl/blob/master/content/data-structures/HashMap.h

**Comment by simonlindholm** [comment]
or, oh, custom hash function. That's fair, I guess, or we could just add a comment about it.

**Comment by Chillee** [comment]
Yeah, using the default hash function is very dangerous for `gp_hash_table`, since power of 2 hashing + open addressing makes it very vulnerable to bad hashes.

For example, one case that shows up commonly is insertion of `a`, `a<<1`,`a<<2`, etc.
