### ISSUE TITLE
Improved Geometry Implementations

### ISSUE THREAD

**Issue by Chillee** [kth-competitive-programming/kactl#95]
Some functions that I think can be shortened/improved (usually because I've seen shorter ones elsewhere), along with my guesses on how many lines can be saved.

- [x] [ConvexHull.h](https://gist.github.com/Chillee/0b60cfa96626cb14325fcd0064b05e36#file-convex-cpp) ~5 lines (actually 7 lines)
- [x] [PolygonDiameter.h](https://gist.github.com/Chillee/0b60cfa96626cb14325fcd0064b05e36#file-convex-cpp) ~ 8 lines (actually 8 lines)
- [x] [PointInsideHull.h](https://gist.github.com/Chillee/0b60cfa96626cb14325fcd0064b05e36#file-convex-cpp) ~7 lines (actually 9 lines)
- [x] [LineHullIntersection.h](https://codeforces.com/blog/entry/48868) ~30 lines
- [x] PolygonCut.h
- [x] Minimum Enclosing Circle (Tsinghua.pdf) (~15 lines)

**Comment by ecnerwala** [comment]
The Tsinghua Min Enclosing Circle is the standard randomized O(N) algorithm, it just looks like it's O(N^3).

**Comment by Chillee** [comment]
I was talking about this one: 
![image](https://user-images.githubusercontent.com/6355099/57311433-a4f08e80-70b9-11e9-8a5e-01ba570fd5d7.png)

from here: https://github.com/ecnerwala/icpc-book/blob/master/xyz/THU_book.pdf

**Comment by Chillee** [comment]
Everything I wanted to look at has been merged/PR submitted - I'll just open a running issue for the whole notebook.
